kneequery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_kneequery.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dj_kneequery/models.py
from django.db import models
from django.db.models.signals import post_save
from django.db import connection
from .scales import *
from .sql import *


class Patient(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(
            max_length=100,
            default=None,
            blank=True,
            null=True,
            )
    age = models.IntegerField(default=None, blank=True, null=True)
    address = models.CharField(
            max_length=150,
            default=None,
            blank=True,
            null=True,
            )
    number = models.CharField(
            max_length=20,
            default=None,
            blank=True,
            null=True,
            )

    @property
    def operations(self):
        try:
            return self.operation_set.all()
        except Exception:
            return None

    @property
    def is_in_queue(self):
        try:
            print(Queue.objects.filter(patient=self.id).get())
            return Queue.objects.filter(patient=self.id).get()
        except Exception:
            return None

    @property
    def position_in_queue(self):
        with connection.cursor() as c:
            c.execute(get_queue)
            record = next(
                    filter(
                            lambda k: k[1]['id'] == self.id,
                            enumerate(
                                    dictfetchall(c),
                                    start=1
                            )
                    )
            )
        return record[0]

    def __str__(self):
        return self.name


class Examination(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    date = models.DateField(default=None, blank=True, null=True)
    joint = models.CharField(
            max_length=1,
            choices=(("l", "Левый"), ('r', "Правый")),
            default='',
            )
    arthrosis_stage = models.IntegerField(
            choices=((1, 1), (2, 2), (3, 3), (4, 4)),
            default=0,
            )
    treatment = models.CharField(
            max_length=50,
            default=None,
            blank=True,
            null=True,
            )
    examination = models.CharField(
            max_length=25,
            default=None,
            blank=True,
            null=True,
            )

    def __str__(self):
        return str(self.date)

    @property
    def womac(self):
        try:
            return self.womac_set.last()
        except Exception:
            return None

    @property
    def kss(self):
        try:
            return self.kss_set.last()
        except Exception:
            return None

    @property
    def antropometry(self):
        try:
            return self.antropometry_set.last()
        except Exception:
            return None

    @property
    def jk(self):
        try:
            return self.jk_set.last()
        except Exception:
            return None


class Antropometry(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    examination = models.ForeignKey(
            'Examination',
            on_delete=models.CASCADE,
            default=None,
            blank=True,
            null=True,
            )
    height = models.IntegerField(default=None, blank=True, null=True)
    weight = models.IntegerField(default=None, blank=True, null=True)
    bmi = models.FloatField(default=None, blank=True, null=True)

    def save(self, *args, **kwargs):
        try:
            self.bmi = self.weight * 10_000 / (self.height ** 2)
        except Exception:
            self.bmi = 0
        super().save(*args, **kwargs)


class Operation(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    date = models.DateField(default=None, blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1000)


class Queue(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)


class RupivacainAmount(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    operation = models.ForeignKey('Operation', on_delete=models.CASCADE)
    amount = models.FloatField(default=None, blank=True, null=True)


class RupivacainPain(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    amount = models.ForeignKey('RupivacainAmount', on_delete=models.CASCADE)
    lag = models.IntegerField(default=None, blank=True, null=True)
    vas = models.IntegerField(
            choices=tuple(((i, str(i)) for i in range(1, 11))),
            default=1,
            help_text='Pain intensivity',
    )

    class Meta:
        ordering = ['lag']


class TranexamAmount(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    operation = models.ForeignKey('Operation', on_delete=models.CASCADE)
    amount = models.IntegerField(
            choices=((1, '1.0'), (2, '2.0'), ),
            default=1,
            help_text='Tranexam amount',
    )


class TranexamHb(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    amount = models.ForeignKey(
            'TranexamAmount',
            on_delete=models.CASCADE,
            default=None,
            blank=True,
            null=True,
    )
    lag = models.IntegerField(default=None, blank=True, null=True)
    hb = models.IntegerField(default=0, blank=True, null=True)

    class Meta:
        ordering = ['lag']


def save(self, *args, **kwargs):
    self.score = sum(
            (self.__dict__[str(i)] for i in range(1, len(kss_questions)))) / 2
    super(KSS, self).save(*args, **kwargs)


kss_dict = {str(i): models.IntegerField(
        choices=kss_questions[k],
        default=kss_questions[k][0][0],
        help_text=k,
        )
    for i, k in enumerate(kss_questions, start=1)
}
kss_dict['category'] = models.CharField(
        max_length=1,
        choices=kss_category,
        help_text='Категория пациента',
        default=kss_category[0][0],
        )
kss_dict['creation_date'] = models.DateTimeField(auto_now_add=True)
kss_dict['examination'] = models.ForeignKey(
        'Examination',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
        )
kss_dict['score'] = models.IntegerField(default=None, blank=True, null=True)
kss_dict['save'] = save
kss_dict['__module__'] = Patient.__module__

KSS = type('KSS', (models.Model,), kss_dict)


def save(self, *args, **kwargs):
    self.score = sum(
            (self.__dict__[str(i)] for i in range(1, len(womac_questions))))
    super(Womac, self).save(*args, **kwargs)


womac_dict = {str(i): models.IntegerField(choices=(
        (0, 'нет'),
        (1, 'легко'),
        (2, 'умеренно'),
        (3, 'выражено'),
        (4, 'очень сильно')
    ), default=0, help_text=q) for i, q in enumerate(womac_questions, start=1)}
womac_dict['creation_date'] = models.DateTimeField(auto_now_add=True)
womac_dict['examination'] = models.ForeignKey(
        'Examination',
        on_delete=models.CASCADE,
        )
womac_dict['score'] = models.IntegerField(default=None, blank=True, null=True)
womac_dict['save'] = save
womac_dict['__module__'] = Patient.__module__

Womac = type('Womac', (models.Model,), womac_dict)


def save(self, *args, **kwargs):
    self.score = sum(
            (self.__dict__[str(i)] for i in range(1, len(jk_questions))))
    super(JK, self).save(*args, **kwargs)


jk_dict = {str(i): models.IntegerField(
        choices=jk_questions[q],
        default=jk_questions[q][0][0],
        help_text=q,
        )
    for i, q in enumerate(jk_questions, start=1)}
jk_dict['creation_date'] = models.DateTimeField(auto_now_add=True)
jk_dict['examination'] = models.ForeignKey(
        'Examination',
        on_delete=models.CASCADE,
        )
jk_dict['score'] = models.IntegerField(default=None, blank=True, null=True)
jk_dict['save'] = save
jk_dict['__module__'] = Patient.__module__

JK = type('JK', (models.Model,), jk_dict)


def create_scales_on_examination(instance, created, **kwargs):
    if created:
        Womac.objects.create(examination=instance)
        KSS.objects.create(examination=instance)
        JK.objects.create(examination=instance)
        Antropometry.objects.create(examination=instance)


def create_measurements_on_operation(instance, created, **kwargs):
    if created:
        TranexamAmount.objects.create(operation=instance)
        RupivacainAmount.objects.create(operation=instance)


post_save.connect(create_scales_on_examination, sender=Examination)
post_save.connect(create_measurements_on_operation, sender=Operation)

templates/base.html
<html>
<head>
    <title>Kneequery</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" href="{% static 'main.css'%}">

</head>
<body>
<header>
        <div class="header" role="alert">
        {% if user.is_authenticated %}
            <p>Hi, {{ user.username }}! <a href="{% url 'logout' %}">Log Out</a></p>
        {% else %}
            <p>You are not logged in. <a href="{% url 'admin:login' %}">Log In</a></p>
        {% endif %}
            <p>
                <a href="{% url 'queue' %}" class="btn btn-primary" role="button">Queue</a>
                <a href="{% url 'patients' %}" class="btn btn-primary" role="button">Patients</a>
                <a href="{% url 'admin:index' %}" class="btn btn-primary" role="button">Admin</a>
            </p>

<form action="{% url 'search'  %}">
    <div class="input-group mb-3">
        <input type="search" name="query" class="form-control" placeholder="e.g. Ivanov">
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </div>
    </div>
</form>

        </div>
    </header>
<div class="container-fluid">
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</div>
</body>
</html>

templates/detailed_patients.html
{% extends 'base.html' %}

{% block content %}
<div class="card bg-light mb-3">
  <div class="card-body">
    <h2 class="card-title">{{object.name}}</h2>
    <div class="card-text">
        {% if object.is_in_queue %}
        <div># {{object.position_in_queue}} in Queue
        <a class="btn btn-danger btn-sm ml-2" href="{% url 'delete_from_queue' object.id %}" role="button">Delete patient from queue</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'add_to_queue' object.id %}" role="button">Add patient to queue</a>
        {% endif %}
        </div>
          <br>
        <table class="table compact-table">
            <tbody>
                <tr class="compact">
                    <th scope="row">Age</th>
                    <td>{{object.age}}</td>
                </tr>
                <tr class="compact">
                    <th scope="row">Address</th>
                    <td>{{object.address}}</td>
                </tr>
                <tr class="compact">
                    <th scope="row">Number</th>
                    <td>{{object.number}}</td>
                </tr>
            </tbody>
        </table>
        <br>
        <a class="btn btn-outline-dark" href="{% url 'admin:dj_kneequery_patient_change' object.id %}" role="button">Change personal info</a>
    </div>
  </div>
</div>

<div class="card bg-light mb-3">
  <h6 class="card-header text-muted">
      <div class="float-left mt-2">Operations</div>
        <a class="btn btn-primary float-right" href="{% url 'create_operation' object.id %}" role="button">Add Operation</a>
  </h6>
  <div class="card-body">
    <h2 class="card-title"></h2>
    <div class="card-text">
        {% if object.operations %}
    {% for operation in object.operations %}
<div class="operation">
    <h3>{{ operation.name }}</h3>
    <div class="text-muted">Оперирован {{ operation.date }}</div>
    <p>{{ operation.description }}</p>
    <a class="btn btn-outline-dark" href="{% url 'admin:dj_kneequery_operation_change' operation.id %}" role="button">Change operation info</a>
    <br><br>
    <details>
        <summary class="btn btn-primary"><div class="d-inline">Details</div></summary>
    {% for tr in operation.tranexamamount_set.all %}
        <h5 class="mt-4">Введено транексама: <a class="btn btn-outline-secondary" href="{% url 'admin:dj_kneequery_tranexamamount_change' tr.id %}" role="button">{{tr.amount}}</a></h5>
        {% for t in tr.tranexamhb_set.all %}
            <table class="table compact-table">
                <tbody>
                    <tr class="compact">
                        <th scope="row"><a href="{% url 'admin:dj_kneequery_tranexamhb_change' t.id %}">{{t.lag}} h</a></th>
                        <td><a href="{% url 'admin:dj_kneequery_tranexamhb_change' t.id %}">{{t.hb}}</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'admin:dj_kneequery_tranexamhb_delete' t.id %}" role="button">X</a></td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
        <p><a class="btn btn-info" href="{% url 'create_tranexamhb' tr.id %}" role="button">Add Hb evaluation</a></p>
    {% endfor %}
    {% for rp in operation.rupivacainamount_set.all %}

    <h5 class="mt-4">Введено рупивакаина: <a class="btn btn-outline-secondary" href="{% url 'admin:dj_kneequery_rupivacainamount_change' rp.id %}" role="button">{{rp.amount}}</a></h5>
        {% for p in rp.rupivacainpain_set.all %}
            <table class="table compact-table">
                <tbody>
                    <tr class="compact">
                        <th scope="row"><a href="{% url 'admin:dj_kneequery_rupivacainpain_change' p.id %}">{{p.lag}} h</a></th>
                        <td><a href="{% url 'admin:dj_kneequery_rupivacainpain_change' p.id %}">{{p.vas}}</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'admin:dj_kneequery_rupivacainpain_delete' p.id %}" role="button">X</a></td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
        <p><a class="btn btn-info" href="{% url 'create_rupivacainpain' rp.id %}" role="button">Add pain evaluation</a></p>
    {% endfor %}
</div>
    {% endfor %}

  </details>
{% else %}
<div class="alert alert-secondary" role="alert">
    Не оперирован <a class="btn btn-outline-secondary" href="{% url 'create_operation' object.id %}" role="button">Add operation info</a>
</div>
{% endif %}
    </div>
  </div>
</div>

<div class="card bg-light mb-3">
  <h6 class="card-header text-muted">
      <div class="float-left mt-2">Examinations</div>
      <a class="btn btn-primary float-right" href="{% url 'create_examination' object.id %}" role="button">Add Examination</a>
  </h6>
  <div class="card-body container-fluid">
    <div class="card-text">
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Date</th>
        <th scope="col">Weight</th>
        <th scope="col">Height</th>
        <th scope="col">BMI</th>
        <th scope="col">Joint</th>
        <th scope="col">Arthrosis Stage</th>
        <th scope="col">WOMAC</th>
        <th scope="col">Joseph & Kaufmann</th>
        <th scope="col">KSS</th>
        <th scope="col">Category</th>
    </tr>
    </thead>
    <tbody>
    {% for e in object.examination_set.all %}
        <tr>
            <th scope="row"><a href="{% url 'admin:dj_kneequery_examination_change' e.id %}">{{ forloop.counter }}</a></th>
            <td><a href="{% url 'admin:dj_kneequery_examination_change' e.id %}">{{e.date}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_antropometry_change' e.antropometry.id %}">{{e.antropometry.weight}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_antropometry_change' e.antropometry.id %}">{{e.antropometry.height}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_antropometry_change' e.antropometry.id %}">{{e.antropometry.bmi}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_examination_change' e.id %}">{% if e.joint == "l" %}left{% else %}right{% endif %}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_examination_change' e.id %}">{{e.arthrosis_stage}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_womac_change' e.womac.id %}">{{e.womac.score}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_jk_change' e.jk.id %}">{{e.jk.score}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_kss_change' e.kss.id %}">{{e.kss.score}}</a></td>
            <td><a href="{% url 'admin:dj_kneequery_kss_change' e.kss.id %}">{{e.kss.category}}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>
  </div>
</div>


{% endblock content %}

templates/patients.html
{% extends 'base.html' %}

{% block content %}
    <a class="btn btn-info" href="{% url 'admin:dj_kneequery_patient_add' %}" role="button">Add new patient</a>
    <br><br>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col"><a href="{% url 'patients' %}?order={{ filter_name }}">Name</a></th>
        <th scope="col" class="d-none d-lg-table-cell text-center"><a href="{% url 'patients' %}?order={{ filter_age }}">Age</a></th>
        <th scope="col" class="d-none d-lg-table-cell text-center"><a href="{% url 'patients' %}?order={{ filter_operated }}">Operated</a></th>
        <th scope="col" class="d-none d-lg-table-cell text-center"><a href="{% url 'patients' %}?order={{ filter_womac }}">WOMAC</a></th>
        <th scope="col" class="d-none d-lg-table-cell text-center"><a href="{% url 'patients' %}?order={{ filter_jk }}">Joseph & Kaufmann</a></th>
        <th scope="col" class="text-center"><a href="{% url 'patients' %}?order={{ filter_KSS }}">KSS</a></th>
        <th scope="col" class="text-center"><a href="{% url 'patients' %}?order={{ filter_category }}">Category</a></th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
        {% for patient in object_list %}
        <tr>
            <th scope="row" class="align-middle">{{ forloop.counter }}</th>
            <td class="align-middle"><a href="{% url 'detailed_patients' patient.id %}">{{patient.name}}</a></td>
            <td class="d-none d-lg-table-cell text-center align-middle">{{patient.age}}</td>

            {% if patient.operated %}
                <td class="d-none d-lg-table-cell text-center align-middle">+</td>
            {% else %}
                <td class="d-none d-lg-table-cell text-center align-middle">-</td>
            {% endif %}

            {% if patient.womac %}
                <td class="d-none d-lg-table-cell text-center align-middle">{{patient.womac}}</td>
            {% else %}
                <td class="d-none d-lg-table-cell text-center align-middle">-</td>
            {% endif %}

            {% if patient.jk %}
                <td class="d-none d-lg-table-cell text-center align-middle">{{patient.jk}}</td>
            {% else %}
                <td class="d-none d-lg-table-cell text-center align-middle">-</td>
            {% endif %}

            {% if patient.kss %}
                <td class="text-center align-middle">{{patient.kss}}</td>
            {% else %}
                <td class="text-center align-middle">-</td>
            {% endif %}

            {% if patient.category %}
                <td class="text-center align-middle">{{patient.category}}</td>
            {% else %}
                <td class="text-center align-middle">-</td>
            {% endif %}

            <td><a class="btn btn-danger btn-delete" href="{% url 'admin:dj_kneequery_patient_delete' patient.id %}" role="button">x</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/queue.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col" class="text-center">Age</th>
        <th scope="col" class="text-center">WOMAC</th>
        <th scope="col" class="text-center">KSS</th>
        <th scope="col" class="text-center">Category</th>
    </tr>
    </thead>
    <tbody>
        {% for patient in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'detailed_patients' patient.id %}">{{patient.name}}</a></td>
            <td class="text-center">{{patient.age}}</td>
            <td class="text-center">{{patient.womac}}</td>
            <td class="text-center">{{patient.kss}}</td>
            <td class="text-center">{{patient.category}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/search.html
{% extends 'base.html' %}

{% block content %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
        {% for patient in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'detailed_patients' patient.id %}">{{patient.name}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}